### ISSUE TITLE
Compiling the firmware fails with ESPHome 2021.10.0

### ISSUE THREAD

**Issue by tunip** [persuader72/esphome-components#5]
Hello, with ESPHome 2021.10.0 the compile of the firmware fails.

````
Compiling .pioenvs/buro-thermostat/src/esphome/components/shelly_dallas/shelly_dallas_component.cpp.o
Compiling .pioenvs/buro-thermostat/src/esphome/components/shelly_dallas/shelly_esp_one_wire.cpp.o
In file included from src/esphome/components/shelly_dallas/shelly_dallas_component.h:5:0,
                 from src/esphome/components/shelly_dallas/shelly_dallas_component.cpp:1:
src/esphome/components/shelly_dallas/shelly_esp_one_wire.h:4:33: fatal error: esphome/core/esphal.h: No such file or directory
 #include "esphome/core/esphal.h"
                                 ^
compilation terminated.
*** [.pioenvs/buro-thermostat/src/esphome/components/shelly_dallas/shelly_dallas_component.cpp.o] Error 1
In file included from src/esphome/components/shelly_dallas/shelly_esp_one_wire.cpp:1:0:
src/esphome/components/shelly_dallas/shelly_esp_one_wire.h:4:33: fatal error: esphome/core/esphal.h: No such file or directory
 #include "esphome/core/esphal.h"
                                 ^
compilation terminated.
*** [.pioenvs/buro-thermostat/src/esphome/components/shelly_dallas/shelly_esp_one_wire.cpp.o] Error 1
========================== [FAILED] Took 4.36 seconds ==========================
```

**Comment by alexander-vitishchenko** [comment]
Hi @persuader72,

Apologies for disturbing! Just few questions:
- have you had a chance to look to compiler issue and resolve it with you local branch?
- can you please share the link with your pull request to ESPHome team, I'll try to add some comments from my side and upvote your request. By the way - I've created such feature request already, perhaps worth linking them together - https://github.com/esphome/feature-requests/issues/1456
- did you consider HACS for deploying your components? IMHO this would be easier to deploy new versions of your integration for new users 

Thank you,
Alexander

**Comment by bogdansmc** [comment]
Hi @persuader72 

Can you share your separate branch that works with new esphome releases with me too?

**Comment by persuader72** [comment]
Hi @alexander-vitishchenko, @bogdansmc 

I pushed a new **dev** branch with the patch for compiling the DHT sensor, 
I already checked the the plugin compile without errors with the 2021.10.2  but I can't actually test it because I don't have the DHT sensor.
Please let me know I the patches are working correctly.

**Comment by persuader72** [comment]
@alexander-vitishchenko 

The pull request is the following:  https://github.com/esphome/esphome/pull/1346

About HACS the problem, I think, is that HomeAssistant and EspHome are two different projects, and in the HACS there aren't  EspHome custom components but, HomeAssistant integrations, (If I understand correctly)

It would be nice if we can find a corresponding repository of  HACS for EspHome components.

**Comment by alexander-vitishchenko** [comment]
> Hi @alexander-vitishchenko, @bogdansmc 
> 
> 
> 
> I pushed a new **dev** branch with the patch for compiling the DHT sensor, 
> 
> I already checked the the plugin compile without errors with the 2021.10.2  but I can't actually test it because I don't have the DHT sensor.
> 
> Please let me know I the patches are working correctly.
> 
> 
> 
> 
> 
> 
> 
> 

Thank you! I'll test it tomorrow!

**Comment by alexander-vitishchenko** [comment]
I've just finished overnight testing for DHT11 sensor - seems to be working fine!

**Comment by alexander-vitishchenko** [comment]
As for HACS - I couldn't find an easy way to install ESPHome custom components, but only for Home Assistant Core :(

**Comment by alexander-vitishchenko** [comment]
So maybe we should keep asking ESPHome development team to review/adjust/merge your pull request. This seems to be the best option to me, but possibly introducing a bit of short and longer term overhead for ESPHome team

**Comment by tunip** [comment]
Many thx @persuader72

Shelly Dallas add-on works again. Would also suggest that we keep asking ESPHome development team to merge your pull request.

**Comment by cg089** [comment]
I unfortunately have the same error:
src/esphome/components/shelly_dht/dht.h:38:16: error: 'GPIOPin' has not been declared

But I don't know what to do with pull requests or so. I tried to downgrade esphome which seems not possible. I looked at the files I might have to change manually https://github.com/esphome/esphome/pull/1346/files but the subfolder /components/dallas does not even exist :(
Any more ideas?

**Comment by dawsmac** [comment]
@persuader72 cheer for spending the time getting this added :) 

I am gettig the same issue tho, even when trying to add the "custom_components" folder. 

maybe I am missing something.

What steps do I need to follow to take advantage of a different branch as stated above ? Please 

`-- <ESP8266WiFi> 1.0
|-- <ArduinoJson-esphomelib> 5.13.3
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <noise-c> 0.1.4
|   |-- <libsodium> 1.10018.1
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
Compiling .pioenvs/underfloor-heating/src/esphome/components/shelly_dallas/shelly_dallas_component.cpp.o
Compiling .pioenvs/underfloor-heating/src/esphome/components/shelly_dallas/shelly_esp_one_wire.cpp.o
Compiling .pioenvs/underfloor-heating/src/esphome/components/switch/automation.cpp.o
Compiling .pioenvs/underfloor-heating/src/esphome/components/switch/switch.cpp.o
In file included from src/esphome/components/shelly_dallas/shelly_dallas_component.h:5:0,
                 from src/esphome/components/shelly_dallas/shelly_dallas_component.cpp:1:
src/esphome/components/shelly_dallas/shelly_esp_one_wire.h:4:33: fatal error: esphome/core/esphal.h: No such file or directory
 #include "esphome/core/esphal.h"
                                 ^
compilation terminated.
*** [.pioenvs/underfloor-heating/src/esphome/components/shelly_dallas/shelly_dallas_component.cpp.o] Error 1
In file included from src/esphome/components/shelly_dallas/shelly_esp_one_wire.cpp:1:0:
src/esphome/components/shelly_dallas/shelly_esp_one_wire.h:4:33: fatal error: esphome/core/esphal.h: No such file or directory
 #include "esphome/core/esphal.h"
                                 ^
compilation terminated.
*** [.pioenvs/underfloor-heating/src/esphome/components/shelly_dallas/shelly_esp_one_wire.cpp.o] Error 1
========================== [FAILED] Took 2.28 seconds ==========================
`

**Comment by tunip** [comment]
@dawsmac Sorry to ask, but are you really using the dev branch?
https://github.com/persuader72/esphome-components/tree/dev

**Comment by dawsmac** [comment]
@tunip I am glad you asked 👍 after adding the correct flag all is good now Thanks 

git clone --branch dev  https://github.com/persuader72/esphome-components.git  custom_components

**Comment by tunip** [comment]
@cg089 Maybe the example for the DHT sensor is also wrong. Could you try:
```
sensor:
  - platform: shelly_dht
    pin_a: GPIO3
    pin_b: GPIO0
```

**Comment by cg089** [comment]
@tunip 
thats excactly what's in my config already:

`...

sensor:
  - platform: shelly_dht
    model: DHT11
    pin: GPIO3
    pin_a: GPIO0
    temperature:
      name: "${devicename} Temperatur"
    humidity:
      name: "${devicename} Luftfeuchtigkeit"
    update_interval: 60s`

It compiled perfect with ESPHome 2021.08 and worked flawlessly since then.
However I wanted to upgrade the DHT11 with a DHT22 and recompile. Now it gets the following errors, even with the DHT11 config which worked before:

`Compiling /data/shelly-garage-links/.pioenvs/shelly-garage-links/src/esphome/components/shelly_dht/dht.cpp.o
Compiling /data/shelly-garage-links/.pioenvs/shelly-garage-links/src/esphome/components/web_server_base/web_server_base.cpp.o
In file included from src/esphome/components/shelly_dht/dht.cpp:1:0:
src/esphome/components/shelly_dht/dht.h:38:16: error: 'GPIOPin' has not been declared
   void set_pin(GPIOPin *pin, GPIOPin *pin_a) { pin_in_ = pin; pin_out_ = pin_a; }
                ^
src/esphome/components/shelly_dht/dht.h:38:30: error: 'GPIOPin' has not been declared
   void set_pin(GPIOPin *pin, GPIOPin *pin_a) { pin_in_ = pin; pin_out_ = pin_a; }
                              ^
src/esphome/components/shelly_dht/dht.h:54:3: error: 'GPIOPin' does not name a type
   GPIOPin *pin_in_;
   ^
src/esphome/components/shelly_dht/dht.h:55:3: error: 'GPIOPin' does not name a type
   GPIOPin *pin_out_;
   ^
src/esphome/components/shelly_dht/dht.h: In member function 'void esphome::dht::DHT::set_pin(int*, int*)':
src/esphome/components/shelly_dht/dht.h:38:48: error: 'pin_in_' was not declared in this scope
   void set_pin(GPIOPin *pin, GPIOPin *pin_a) { pin_in_ = pin; pin_out_ = pin_a; }
                                                ^
src/esphome/components/shelly_dht/dht.h:38:63: error: 'pin_out_' was not declared in this scope
   void set_pin(GPIOPin *pin, GPIOPin *pin_a) { pin_in_ = pin; pin_out_ = pin_a; }
                                                               ^
src/esphome/components/shelly_dht/dht.cpp: In member function 'virtual void esphome::dht::DHT::setup()':
src/esphome/components/shelly_dht/dht.cpp:12:9: error: 'class esphome::dht::DHT' has no member named 'pin_in_'
   this->pin_in_->pin_mode(INPUT);
         ^
src/esphome/components/shelly_dht/dht.cpp:12:27: error: 'INPUT' was not declared in this scope
   this->pin_in_->pin_mode(INPUT);
                           ^
src/esphome/components/shelly_dht/dht.cpp:13:9: error: 'class esphome::dht::DHT' has no member named 'pin_out_'
   this->pin_out_->pin_mode(OUTPUT);  
         ^
src/esphome/components/shelly_dht/dht.cpp:13:28: error: 'OUTPUT' was not declared in this scope
   this->pin_out_->pin_mode(OUTPUT);  
                            ^
src/esphome/components/shelly_dht/dht.cpp:14:9: error: 'class esphome::dht::DHT' has no member named 'pin_out_'
   this->pin_out_->digital_write(true);  
         ^
src/esphome/components/shelly_dht/dht.cpp: In member function 'virtual void esphome::dht::DHT::dump_config()':
src/esphome/components/shelly_dht/dht.cpp:18:31: error: 'class esphome::dht::DHT' has no member named 'pin_in_'
   LOG_PIN("  Pin In: ", this->pin_in_);
                               ^
src/esphome/components/shelly_dht/dht.cpp:18:38: error: 'LOG_PIN' was not declared in this scope
   LOG_PIN("  Pin In: ", this->pin_in_);
                                      ^
src/esphome/components/shelly_dht/dht.cpp:19:32: error: 'class esphome::dht::DHT' has no member named 'pin_out_'
   LOG_PIN("  Pin Out: ", this->pin_out_);
                                ^
src/esphome/components/shelly_dht/dht.cpp: In member function 'bool esphome::dht::DHT::read_sensor_(float*, float*, bool)':
src/esphome/components/shelly_dht/dht.cpp:89:11: error: 'class esphome::dht::DHT' has no member named 'pin_out_'
     this->pin_out_->digital_write(false);
           ^
src/esphome/components/shelly_dht/dht.cpp:92:30: error: 'delayMicroseconds' was not declared in this scope
       delayMicroseconds(18000);
                              ^
src/esphome/components/shelly_dht/dht.cpp:94:28: error: 'delayMicroseconds' was not declared in this scope
       delayMicroseconds(500);
                            ^
src/esphome/components/shelly_dht/dht.cpp:95:13: error: 'class esphome::dht::DHT' has no member named 'pin_out_'
       this->pin_out_->digital_write(true);
             ^
src/esphome/components/shelly_dht/dht.cpp:98:29: error: 'delayMicroseconds' was not declared in this scope
       delayMicroseconds(2000);
                             ^
src/esphome/components/shelly_dht/dht.cpp:100:28: error: 'delayMicroseconds' was not declared in this scope
       delayMicroseconds(800);
                            ^
src/esphome/components/shelly_dht/dht.cpp:103:11: error: 'class esphome::dht::DHT' has no member named 'pin_out_'
     this->pin_out_->digital_write(true);
           ^
src/esphome/components/shelly_dht/dht.cpp:104:25: error: 'delayMicroseconds' was not declared in this scope
     delayMicroseconds(40);
                         ^
src/esphome/components/shelly_dht/dht.cpp:110:36: error: 'micros' was not declared in this scope
       uint32_t start_time = micros();
                                    ^
src/esphome/components/shelly_dht/dht.cpp:113:21: error: 'class esphome::dht::DHT' has no member named 'pin_in_'
       while (!this->pin_in_->digital_read()) {
                     ^
src/esphome/components/shelly_dht/dht.cpp:129:20: error: 'class esphome::dht::DHT' has no member named 'pin_in_'
       while (this->pin_in_->digital_read()) {
                    ^
*** [/data/shelly-garage-links/.pioenvs/shelly-garage-links/src/esphome/components/shelly_dht/dht.cpp.o] Error 1
========================== [FAILED] Took 3.65 seconds ==========================
`

**Comment by cg089** [comment]
It works with the dev branch.

**Comment by persuader72** [comment]
@cg089  sorry for the late reply, the dev branch is working fine for you now? In that case, I will merge the dev branch in the master.

**Comment by cg089** [comment]
> @cg089 sorry for the late reply, the dev branch is working fine for you now? In that case, I will merge the dev branch in the master.

Yep, everything working with dev branch! Thank you!

**Comment by srnoth** [comment]
@persuader72 did the official merge request get cancelled? Any explanation from the ESP Home devs?

https://github.com/esphome/esphome/pull/1346

**Comment by tunip** [comment]
The dev-branch is working fine. I close this issue now.
